- hosts: mygroup-play
  tags: base
  become: true
  tasks:
    - debug:
        msg: "I'm in group 'mygroup'"

- hosts: onlyfoo
  tags: workstation
  become: true
  tasks:
    - debug:
        msg: "I'm in group 'onlyfoo'"

- hosts: onlybar
  tasks:
    - debug:
        msg: "I'm in group 'onlybar'"

- name: configure ansible-pull
  tags: workstation
  become: true
  hosts: all
  roles:
    - role: ansible-pull
      ansible_pull_url: https://github.com/dominik-ba/ansible-pull.git
