- name: desktop demo debug msg
  hosts: desktop
  tasks:
    - debug:
        msg: "I'm in group 'desktop'"

- name: headless demo debug msg
  hosts: headless
  tasks:
    - debug:
        msg: "I'm in group 'headless'"

- name: cowsay - demo
  hosts: all
  roles:
    - role: cowsay

- name: setup
  hosts: usbhost
  roles:
    - role: usbserver
