- name: Download vhusbd to usr bin
  become: true
  ansible.builtin.get_url:
    url: https://www.virtualhere.com/sites/default/files/usbserver/vhusbdarm
    dest: /usr/bin/vhusbdarm
    mode: "555"
    group: ansible

- name: add usbdaemon start in rc.local
  become: true
  ansible.builtin.lineinfile:
    path: /etc/rc.local
    insertbefore: "^exit"
    line: "/usr/bin/vhusbdarm -b &"
