---
- name: install cowsay
  ansible.builtin.apt:
    name:
      - cowsay
    state: present
  when: ansible_facts.os_family == "Debian"

- name: hello
  command: "/usr/games/cowsay 'hello'"
  register: cowsay

- name: cowsay out
  debug:
    var: cowsay
