- name: create ansible user
  user:
    name: ansible
    system: yes

- name: copy sudoers_ansible
  become: true
  copy:
    src: files/sudoers_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440

- name: system setup | cron | schedule automatic ansible provisioning
  become: true
  tags: cron
  cron:
    name: "ansible provision"
    user: ansible
    hour: "{{ ansible_cron_hour | default('*') }}"
    minute: "{{ ansible_cron_minute | default('*/30') }}"
    job: "ansible-pull -o -U https://github.com/dominik-ba/ansible-pull.git"

- name: system setup | cron | schedule ansible cleanup at boot
  become: true
  tags: cron
  cron:
    name: "ansible refresh at boot"
    user: ansible
    special_time: reboot
    job: "/bin/rm -rf /home/ansible/.ansible"
